### PR TITLE
Add support for reversed version range (e.g. "<2.0,>1.0")

### LINKED ISSUE #455: VersionRange breaks if range is not in order
I am not 100% sure this is a bug or may be expected and/or wanted. As mentioned before i have my own incarnation of rez-pip mostly for windows versions. It fails when installing requests with dependencies because the urllib3 requirement is stated in "inverse" order.
I am unsure where this comes from. It seems fine in the setup.py of requests but it is inverted on pypi already so it is not being interpreted wrong within rez or distlib.

Anyways it is easy to reproduce:

```
from rez.vendor.version.version import VersionRange
print VersionRange('>=1.21.1,<1.23')
print VersionRange('<1.23,>=1.21.1')
```

The first one works the second breaks with a Syntax Error:

`PackageRequest(u'urllib3-<1.23,>=1.21.1') raised VersionError(u"Syntax error in version range '<1.23,>=1.21.1': Syntax error in version range '<1.23,>=1.21.1'",)`

### PR DESCRIPTION
**Pull request by instinct-vfx**
Fixes #455 by allowing both ascending and descending version ranges. Thanks to  @PatrickFoerster who implemented this here.

### CODE REVIEW

**Comment by skral** [comment]
PR is missing tests. I created a separate [PR](https://github.com/instinct-vfx/rez/pull/5) on @instinct-vfx repository to get those merged into this PR as well.

@instinct-vfx Is there a better way to add code to your PR?

**Comment by instinct-vfx** [comment]
Sorry for taking so long. I somehow missed your input completely :( I merged your fixes and they are added to this PR. @nerdvegas : Is there still anything missing from this PR i need to add?

**Comment by nerdvegas** [comment]
Hey Thorsten,

I'll take a look soon, cheers. Working on a new feature atm (yay!) then
should be slowly getting through these outstanding PRs, as well as dealing
with other misc bugs and minor feature additions.

Thx
A

**Comment by instinct-vfx** [comment]
I just wanted to give this a little nudge, as it is currently the only difference from our internal releases to official ones and i could stop merging on every release and instead go back to official ones :)

**Comment by nerdvegas** [comment]
Noted, will aim to have this merged soon.
Thx
A

**Comment by instinct-vfx** [comment]
I have updated this PR with the latest release tag.

**Comment by instinct-vfx** [comment]
Did a rebase in the source branch for internal release.

**Comment by nerdvegas** [comment]
Let me know when this is in a good state, will take a look pretty soon.

**Comment by instinct-vfx** [comment]
I did not manage to properly revert this into a correct state. Sorry for that. I created a new PR that includes all changes of the original PR and is based of the current mast. @skral  Sorry for fubaring the history here, but all your changes are in the new PR and i credited you there. I shall take more care in the future:

https://github.com/nerdvegas/rez/pull/618

**Pull request closed without merging**
