### PR TITLE
revert progress iteration and update vendored

### PR DESCRIPTION
**Pull request by maxnbk**
Addresses #765 and updates version of progress library, adding section in vendor readme which did not exist.

### CODE REVIEW

**Comment by JeanChristopheMorinPerso** [comment]
It's just annoying to not see the actions run when the branch comes from fork.

**Comment by maxnbk** [comment]
Yeah, definitely, maybe I'll start pushing to branches on the main repo... I guess that would be a good use of contributor privs..

**Comment by nerdvegas** [comment]
Does anyone know if it works if your own account has Actions access also?

A

**Comment by maxnbk** [comment]
It can, but only on your own fork, not on the PR to the nerdvegas repo.
I just got added to beta yesterday and planned to try it out.

**Comment by maxnbk** [comment]
got the actions running on my fork, and it's passing.

**Comment by JeanChristopheMorinPerso** [comment]
@maxnbk From what I read, it should work. See https://github.community/t5/GitHub-Actions/GitHub-Action-workflow-is-executed-for-a-PR-from-a-forked-repo/td-p/29579 and https://github.community/t5/GitHub-Actions/Run-a-GitHub-action-on-pull-request-for-PR-opened-from-a-forked/m-p/31147#M690.

We need to add the `pull_request` event as a trigger.

**Comment by maxnbk** [comment]
> We need to add the `pull_request` event as a trigger.
Allan had this pushed to master just yesterday, so I might have to re-test.

**Pull request merged**
