### PR TITLE
Added appveyor config

### PR DESCRIPTION
**Pull request by skral**
In the wake of the open source initiative I think a appveyor config might help.
Initial config which runs all the tests. Unfortunately one test fails right now. Didn't look into why.

### CODE REVIEW

**Comment by instinct-vfx** [comment]
Interesting. AFAIK Appveyor is also free for open source projects. Can we have something there that is accessible for everyone? (We do use AppVeyor here in product dev, but i am not involved with that and don't really know the service)

**Comment by skral** [comment]
Yeah, it's free for open source projects. Haven't used it extensively either, don't know if you can see the test reports but you can at least use the icon in the readme to show if the project is passing all the tests right now. I think it would help everyone in being more confident about the latest changes.

**Comment by nerdvegas** [comment]
Continuous testing is a great addition, thanks Sebastian. Will have this
merged soonish.

A

**Comment by mottosso** [comment]
Yes, it's free for open source and it shows you test reports similar to Travis. Here's an example of what that looks like for one of my projects.

- https://ci.appveyor.com/project/mottosso/pyblish/build/199
- https://travis-ci.org/pyblish/pyblish-base/builds/153266170
- https://github.com/pyblish/pyblish-base/pull/292

Including the Travis equivalent for completeness.

Any questions about using it, I'd be happy to help.

**Comment by nerdvegas** [comment]
Closed as we're now using GitHub Actions: https://github.com/nerdvegas/rez/pull/750

**Pull request closed without merging**
