### PR TITLE
Gh actions - first pass

### PR DESCRIPTION
**Pull request by nerdvegas**
Notes:
* Windows is not passing, help appreciated! (Cmake related?)
* Badges don't work, I don't know why.

A couple of test-related things were changed:
* There was a bug causing only the first shell to be tested with funcs decorated in `per_available_shell`.
* Verbosity dropped on solver tests, was making it pretty hard to go through the Actions output.
* The "logging" test was removed. Failed logging won't actually raise an exception, see https://docs.python.org/2/howto/logging.html#exceptions-raised-during-logging. The existing test was actually failing and putting a lot of noise into the test output. Given the simplicity of the test, and the fact that exceptions won't get raised, I thought it best just to remove it.
* We were getting a bug where "decode" was called on the stdout arg from a subprocess.Popen().communicate() call. This is actually an issue with the powershell plugin. It was using universal_newlines=True, which changes the return type; see https://docs.python.org/3.4/library/subprocess.html#frequently-used-arguments. I am not clear on why this was added so I'm unsure of side effects. However it does seem as though if this is necessary, it could be passed through in `**Popen_args` instead anyway.

One thing we should definitely do is port to pytest and do away with the per_available_shell silliness. I'd be interested in adding a `--test` option to `install.py`, which would then install the rez-selftest tool, and pytest (as a native requirement in the installation venv, not a vendored lib). I think it'd be better to not install rez-selftest if `--test` wasn't specified, since it would require pytest in order to work.

Another thing we should do is update the rez-selftest `-s` arg to take multiple shells, and for each of those, to assert that the shell is available, rather than skip over it if not. Right now it isn't that clear whether a given shell is actually getting tested in the CI; for eg, rez could think the shell is unavailable (which in itself may be a bug). So the way I'd see it working is, we would do the apt-get install etc of the shells we want to test, then pass those shells to rez-selftest also, which would fail if any of those shells are not available / rez doesn't know about them.

### CODE REVIEW

**Comment by KelSolaar** [comment]
> Badges don't work, I don't know why.

They will once you merge the changes into `master` :)

**Comment by KelSolaar** [comment]
Btw are you planning to squash the history?

**Comment by nerdvegas** [comment]
Bam! Of course I need a merge to master first. I'm not sure if there's even
an option for branch-specific badges yet either, there's no mention in the
docs.

History - you mean the run history..? Not even sure if that's possible yet.

**Comment by KelSolaar** [comment]
> History - you mean the run history..? Not even sure if that's possible yet.

Nah, the commit one, it scorched my retina! :)

image

**Comment by nerdvegas** [comment]
Ah right gotcha. Yeah I'll make sure I do that before merge. Had to keep
pushing in order to test.
A

**Comment by KelSolaar** [comment]
Sure absolutely make sense, something I noticed before but they fixed during the last few days is that file parsing errors were creating junk on the left actions sidebar. It is gone now, for the better :)

**Comment by nerdvegas** [comment]
Yeah I've noticed other stuff too. In the Actions tab, the available runs
on the left-hand side appear and disappear at odd times, and sometimes
you're not in the run you'd expect. Definitely still beta. But I bet it's
gonna get so much better. I'm a bit surprised the workflow language is so
limited though, I've already hit a few cases where something like Jinja2
would be really useful.

**Comment by KelSolaar** [comment]
> I'm a bit surprised the workflow language is so
limited though

It is almost exactly the Azure Pipelines stuff, and yeah there are some very frustrating bits! It will get better though, can see things changing on a per-day basis almost!

**Comment by JeanChristopheMorinPerso** [comment]
I'm wondering, should we test on CentOS instead of Ubuntu as CentOS is probably way more used than Ubuntu in VFX?

**Comment by JeanChristopheMorinPerso** [comment]
Well screw my last comment, they don't provide anything other than Ubuntu :( .

**Comment by bfloch** [comment]
Great work!

Windows failing is expected.
It is being addressed in #737 and #703. Waiting for feedback.

We could skip the cmake test on windows for now - I don't believe rez has a strict dependency on cmake. Everything else should pass through.

**Comment by bfloch** [comment]
> windows.yaml
> `# TODO install shells (which ones need installing?)`

PowerShell (5.x) and cmd should be build in Windows. We just need pwsh (PowerShellCore 6.x):
https://github.com/PowerShell/PowerShell/releases

**Comment by bfloch** [comment]
Worth checking if pwsh is not installed by default on all platforms:
https://help.github.com/en/articles/workflow-syntax-for-github-actions#using-a-specific-shell

If not something like might do the trick (just tested locally):
```
steps:
  - name: Install pwsh
    shell: PowerShell
    run: |
      [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
      Invoke-WebRequest http://github.com/PowerShell/PowerShell/releases/download/v6.2.3/PowerShell-6.2.3-win-x64.msi -OutFile PowerShell-6.2.3-win-x64.msi
      Start-Process -Wait -FilePath msiexec -ArgumentList /package, PowerShell-6.2.3-win-x64.msi, /quiet, ADD_EXPLORER_CONTEXT_MENU_OPENPOWERSHELL=1, ENABLE_PSREMOTING=1, REGISTER_MANIFEST=1
```

**Comment by nerdvegas** [comment]
merged: https://github.com/nerdvegas/rez/releases/tag/2.47.3

**Pull request closed without merging**
