### PR TITLE
[wiki] Move update utils into main repo

### PR DESCRIPTION
**Pull request by j0yu**
- [![Wiki][wiki-badge]][wiki-actions] CI to build and generate artefact for wiki repository markdown pages
- Sidebar, Footer, Home and Notes from wiki repository
- `rez/cli/_main.py:setup_parser()` function to return rez CLI's `LazyArgumentParser` 
  - Split from `rez/cli/_main.py:run()` function
  - `rez/cli/_main.py:run()` uses/calls this new `rez/cli/_main.py:setup_parser()` 
- `update.py` combines `wiki/update.sh` and wiki repository's `utils/*` scripts

## update.py

In addition to combining the many update scripts into 1, these changes were also added:

- Generate `Command-Line-Tools.md` from rez CLI's `LazyArgumentParser`
- New arguments parser: <details><summary>python wiki/update-wiki.py --help</summary>

  ```
  usage: update-wiki [-h] [--no-push] [--keep-temp] [--github-repo REPO]
                     [--github-branch BRANCH] [--github-workflow WORKFLOW]
                     [--wiki-url URL] [--wiki-dir DIR]
  
  Update GitHub Wiki
  
  optional arguments:
    -h, --help            show this help message and exit
    --no-push             Don't git commit and push new changes. (default: True)
    --keep-temp           Don't remove temporary wiki repository directory.
                          (default: False)
    --github-repo REPO    Url to GitHub repository without leading github.com/.
                          Overrides environment variable GITHUB_REPOSITORY.
                          (default: nerdvegas/rez)
    --github-branch BRANCH
                          Name of git branch that is generating the Wiki.
                          Overrides environment variable GITHUB_BRANCH.
                          (default: master)
    --github-workflow WORKFLOW
                          Name of GitHub workflow that is generating the Wiki.
                          Overrides environment variable GITHUB_WORKFLOW.
                          (default: Wiki)
    --wiki-url URL        Use this url to git clone wiki from. Overrides
                          environment variable CLONE_URL. (default:
                          git@github.com:nerdvegas/rez.wiki.git)
    --wiki-dir DIR        Use this EMPTY directory to temporarily store cloned
                          wiki. Overrides environment variable TEMP_WIKI_DIR.
                          (default: /home/joseph/repos/rez/wiki/.rez-gen-wiki-
                          tmp)
  ```
  </details>
- Optimised `create_contributors_md()`
- Switched to use `from __future__` statements
- `process_markdown_files()`, now performs substitutions for Footer, Sidebar and Command-Line-Tools. These are also added to `no_toc` list.
  - Was `process.py:if __name__ == '__main__'` from wiki repository
- `process_markdown_files.do_raplace()` function now takes a mapping of substitutions rather than a single substitution pair
- Minor variable names, formatting cleanup

## Wiki Changes

Mostly visual, see https://github.com/wwfxuk/rez/wiki

wiki-sidebar-footer

- Sidebar
  - Icons and named sections
  - Moved unwritten pages into collapsible section
  - Added Wiki CI status
  - Added missing but written pages
- Footer
  - Using shields.io
  - Added slack group link

Here is also a quick look at the new auto-generated [command line tools page](https://github.com/wwfxuk/rez/wiki/Command-Line-Tools).

It's not fully in markdown but it's a passable start.

wiki-cli

[wiki-badge]: https://github.com/wwfxuk/rez/workflows/Wiki/badge.svg?branch=wiki-merge-utils
[wiki-actions]: https://github.com/wwfxuk/rez/actions?query=workflow%3AWiki+branch%3Awiki-merge-utils

### CODE REVIEW

**Comment by nerdvegas** [comment]
Nice one Joe, will be getting to this soon and have been looking over it recently.

**Comment by davidlatwe** [comment]
This Wiki update is awesome ! What's the status of this PR ?

**Comment by nerdvegas** [comment]
I'm keen to get this in, I'd expect it in the next few weeks.

I've recently been assigned 20% of my time to do pure rez dev work so
expect stuff like this to start coming off the backlog and getting merged
to master.

Cheers
A

**Comment by nerdvegas** [comment]
Merged, but @j0yu please be aware that the `Command Line Tools` section isn't working properly :( 

https://github.com/wwfxuk/rez/wiki/Command-Line-Tools

**Comment by j0yu** [comment]
Thanks for the merge! I'll open up a separate issue and PR for it :man_technologist:

**Pull request merged**
